require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/**/*
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*
    - config/environments/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - app/models/friendship.rb
    - spec/factories/friendships.rb
    - spec/models/friendship_spec.rb

Lint/EmptyClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/api/**/*
